CREATE DATABASE otherSide;

USE otherSide;

CREATE TABLE usuario (
idUsuario INT PRIMARY KEY AUTO_INCREMENT,
nome VARCHAR(50) NOT NULL,
senha VARCHAR(50) NOT NULL,
email VARCHAR(50) NOT NULL UNIQUE
);

